- name: install basic tools
  yum: pkg={{item}} state=present
  with_items:
    - dstat
    - lsof
    - bash-completion
    - time
    - tmux
    - git
    - xauth
    - screen
    - nano
    - vim
    - bind-utils
    - nmap-ncat
    - lvm2
    - ntp
    - bzip2

- name: stop cloud-init managing /etc/hosts
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/10_etc_hosts.cfg
    state: present
    regexp: '^manage_etc_hosts'
    line: 'manage_etc_hosts: False'
    create: yes

- name: fix /etc/hosts after cloud-init
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: "^127.0.0.1(.*){{ inventory_hostname }}(.*)"
