---
- name: allow access to NFSv4
  lineinfile:
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited'
  notify: restart iptables

- name: install NFS server packages
  yum:
    name: nfs-utils
    state: present

- name: start and enable rpcbind and nfs-server
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
    - nfs-server

# see https://github.com/ansible/ansible-modules-core/issues/3764
- name: enable rpcbind
  command: "systemctl enable rpcbind"
  register: systemctl_result
  changed_when: systemctl_result.stderr != ''

- name: create exports
  lineinfile:
    dest: /etc/exports
    regexp: "^{{ item.directory }} "
    line: "{{ item.directory }} {{ item.export_options | default(cluster_name+'*(rw)') }}"
  with_items: "{{ exports|default([]) }}"
  notify: restart nfs-server
