- name: Base installation
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - base

- name: Configure common cluster
  hosts:
    - masters
    - nodes
  vars:
    selinux_state: "disabled"
  become: yes
  roles:
    - cluster_common

- name: Volume data directory on HDP nodes
  hosts:
    - masters
    - nodes
  vars:
    pv_path: "/dev/vdb"
  become: yes
  roles:
    - role: persistent_lvm_storage
      vg_name: 'vg_data'
      configure_swap: yes

    - role: volume_data_dir
      data_dir_path: "/hadoop"

- name: Hortonworks common cluster setup
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - hortonworks_common

- name: Configure master
  hosts:
    - masters
  become: yes
  roles:
    - cluster_master
    - ambari_server

- name: Ambari agents
  hosts:
    - masters
    - nodes
  become: yes
  roles:
    - ambari_agents

- name: Provision cluster in ambari using spark blueprint
  hosts:
    - localhost
  become: yes
  vars:
    master_private_ip: "{{ hostvars[groups['masters'][0]]['ansible_ssh_host'] }}"
  roles:
    - ambari_blueprints
