- name: Check for swap
  shell: 'swapon -s | grep -E "^/"'
  register: swap_configured
  ignore_errors: yes

- name: Scan for swap on {{ vg_name }}
  command: lvdisplay {{ vg_name }}/swap
  register: test_lv_swap
  ignore_errors: yes

- name: Create logical volume for swap
  lvol: lv=swap vg={{ vg_name }} size={{ ansible_memtotal_mb * 2 }}M
  when: test_lv_swap.rc==5

- name: Run mkswap on swap lv
  command: mkswap /dev/mapper/{{ vg_name }}-swap
  when: swap_configured|failed

- command: 'swapon /dev/mapper/{{ vg_name }}-swap'
  when: swap_configured|failed

- name: Write swap entry in fstab
  mount:
    name: none
    src: /dev/mapper/{{ vg_name }}-swap
    fstype: swap
    state: present
