


# CHECK THE CORRECTNESS ACCORDING TO THE NEEDS/PREFERENCES:

# pouta.csc.fi -> Project -> Compute -> Access & Security -> the service called "Identity"
osAuthName: https://pouta.csc.fi:5001/v2.0

# The name of your CSC project
projectName: Project_2000053

# pouta.csc.fi -> Project -> Network -> Networks -> the name of your project network
networkName: project_2000053
# pouta.csc.fi -> Project -> Network -> Networks -> your project network -> ID in Network Overview
networkId: 88d1d9e6-8038-4258-9e50-91ced4fee75c

bastionFlavor: standard.xlarge
bastionMachineName: bastion_host
bastionSecGroupName: bastion-metapipe

clusterName: csc-spark-cluster
clusterKeyName: my_cluster_key

master:
  flavor: hpc-gen1.8core
  metadataVolumeSize: 100
  nfsSwMainVolumeSize: 75
  nfsSwTmpVolumeSize: 400

# Choose (leave uncommented) exactly 1 of the node groups, and comment the unused one.
nodeGroups:
  - regularHddNodes
#  - ioHddSsdNodes

regularHddNodes:
  numNodes: 2
  flavor: hpc-gen2.48core
  volumeSize: 50

ioHddSsdNodes:
  numNodes: 5
  flavor: io.700GB
  # (SDD volume is defined in the name of an io-flavor)
  hddVolumeSize: 50

# SPARK CONFIGURATION VARIABLES: These values are meant to take effect only when running "create-*" command.
# Changing them when cluster already exists is not recommended.
# The first 4 values: if set to 0, then the value is set according to the Flavor configuration.
sparkMasterVmCores: 0
sparkMasterVmRam: 29
sparkWorkerVmCores: 0
sparkWorkerVmRam: 240
# This value must be non-zero.
sparkExecutorCores: 8

# THESE ARE REQUIRED FOR META-pipe EXECUTION:
swJobTag: csc-AAA
swArtifactsAuthRequired: true
swArtifactsUsername:
swArtifactsPassword:
swArtifactsFilesExec: https://artifacts.sfb.uit.no/jenkins/newpan_tools/39/workflow-assembly-0.1-SNAPSHOT.jar
swArtifactsFileDepsArc: https://artifacts.sfb.uit.no/jenkins/newpan_tools_dependencies/13/metapipe-dependencies.tar.gz
swArtifactsFilesEtc:
#  -




# SHOULD NOT OR MIGHT NOT HAVE NEED TO CHANGE:

regionName: regionOne
bastionAvailZone: nova

bastionKeyName: my_bastion_key

# Can add other admins' IPs here. The IP of the machine that executes the tool will be added automatically.
ipAdmins:

ipCheck: http://checkip.amazonaws.com




# DO NOT CHANGE!

userName: cloud-user

clusterKeyFileName: id_rsa_csc_cluster

imageDefault: CentOS-7.0

# This 4 variables are set by the tool
bastionFloatingIpId:
securityGroupId:
serverGroupId:
swDiskID:

xternFiles:
  ansibleScript: pouta-ansible-cluster
  clusterTestScript: cluster_test.py
  thisJar: Metapipe-cPouta.jar
  config: config.yml
  disablePasswordAuth: _disablePasswordAuth.sh
  ansibleClusterVars: cluster_vars.yaml
  ansibleClusterVarsTemplate: cluster_vars.yaml.template
  sw: sw_files
  diskHelper: _disk.sh
  sparkSetupScript: _setup_cluster.sh
  sparkSetupScriptInit: _init.sh

swInitScript: _init.sh
swPrepareScript: _prepare.sh
swTestScript: _test.sh
swLaunchScript: _run.sh
swStopScript: _stop.sh
swExecutable: workflow-assembly-0.1-SNAPSHOT.jar

# Important dirs, META-pipe location on cluster, NFS shared dirs
nfsSwMainVolumeMount: /export/sw_main
nfsSwTmpVolumeMount: /export/sw_tmp
swFilesDirName: sw
sparkFilesDir: /export/sw_tmp
