- name: install openjdk
  yum: name={{ item }}
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel

- name: fix jdk slow random source
  lineinfile:
    name: /etc/alternatives/jre/lib/security/java.security
    regexp: '^securerandom.source.*'
    line: 'securerandom.source=file:/dev/urandom'
    state: present

- name: open all TCP traffic (actual control done with security rules)
  lineinfile:
    line: "-A INPUT -p tcp -m state --state NEW -m tcp -j ACCEPT"
    dest: /etc/sysconfig/iptables
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited'
  notify: restart iptables
