- name: Destroy a cluster deployed by cluster.yml
  hosts: localhost
  connection: local
  vars:
    cluster_name: "my-oso"
    num_nodes: 2
    remove_masters: no
    remove_nodes: no
    remove_etcd: no
    remove_lb: no
    remove_master_volumes: no
    remove_node_volumes: no
    remove_pvol: no
    remove_security_groups: no

  tasks:
    - name: deprovision node groups
      include: tasks/deprovision_node_group.yml
      with_items: "{{ node_groups }}"
      loop_control:
        loop_var: "node_group"

    - name: remove master VMs
      os_server:
        name: "{{ cluster_name }}-master-{{ item }}"
        state: absent
      with_sequence: count={{ num_masters }}
      when: remove_masters | bool

    - name: remove etcd VMs
      os_server:
        name: "{{ cluster_name }}-etcd-{{ item }}"
        state: absent
      with_sequence: count={{ num_etcd }}
      when: remove_etcd | bool

    - name: remove load balancer VMs
      os_server:
        name: "{{ cluster_name }}-lb-{{ item }}"
        state: absent
      with_sequence: count={{ num_lbs }}
      when: remove_lbs | bool

    - name: remove load_balancer volumes
      os_volume:
        display_name: "{{ cluster_name }}-lb-{{ item }}-data"
        state: absent
      with_sequence: count={{ num_lbs }}
      when: remove_lb_volumes | bool

    - name: remove master volumes
      os_volume:
        display_name: "{{ cluster_name }}-master-{{ item }}-data"
        state: absent
      with_sequence: count={{ num_masters }}
      when: remove_master_volumes | bool

    - name: remove openshift persistent volume
      os_volume:
        display_name: "{{ cluster_name }}-pvol"
        state: absent
      when: remove_pvol | bool

    - name: remove security groups
      os_security_group:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ cluster_name }}-common"
        - "{{ cluster_name }}-master"
      when: remove_security_groups | bool
