---
- set_fact: vm_group={{ vars[vm_group_name] }}

- name: remove {{ vm_group_name }} VMs
  os_server:
    name: "{{ cluster_name }}-{{ vm_group_name }}-{{ item }}"
    state: absent
  with_sequence: count={{ vm_group.num_vms|default(1) }}
  async: 300
  register: async_vm_remove
  when: remove_vms | bool

- name: check VM remove status
  async_status: jid={{ item.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 50
  delay: 3
  with_items: "{{ async_vm_remove.results }}"
  when: remove_vms | bool

- name: remove {{ vm_group_name }} volumes
  include: tasks/vm_group_volume_deprovision.yml
  with_items: "{{ vm_group.volumes|default([]) }}"
  loop_control:
    loop_var: "volume_spec"
  when: remove_volumes | bool

- name: remove ssh config entries
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cluster_name }}-{{ vm_group_name }}-{{ item }}"
  with_sequence: count={{ vm_group.num_vms|default(1) }}

- set_fact: server_group_name={{ vm_group.server_group | default(cluster_name + "-" + server_group_suffix | default(none)) }}
  when: (vm_group.server_group is defined) or (server_group_suffix is defined)

- name: remove server group
  os_server_group:
    state: absent
    name: "{{ server_group_name }}"
    policies: ["anti-affinity"]
  register: server_group_res
  when: server_group_name | default(none) is not none
