---
- name: create .tmuxinator.yaml on disk
  template:
    src: templates/tmuxinator_status.yml.j2
    dest: "{{ ansible_env.HOME }}/{{ cluster_name }}/.tmuxinator.yml"

- name: create .tmux.conf on disk
  template:
    backup: yes
    src: templates/tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
